In [34]:
import pandas as pd
from datetime import datetime

CHECKS_URL = 'https://files.planning.data.gov.uk/reporting/duplicate_entity_expectation.csv?version=20260224'

In [35]:
df = pd.read_csv(CHECKS_URL)

/var/folders/ff/zpylthrn3877kx4h8lxvsvjm0000gn/T/ipykernel_21259/1475414784.py:1: DtypeWarning: Columns (8,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(CHECKS_URL)

for complete match - redirect entity-a to entity-b in the format below

entity-a,301,entity-b,,redirect old entity complete match to LPA entity,today's date,

This should be added to the old-entity.csv in conservation area pipeline

In [36]:
df.head()

,dataset,operation,message,entity_a,entity_a_name,entity_a_organisation,entity_a_organisation_name,entity_a_entry_date,entity_a_end_date,entity_a_geometry,...,entity_b_name,entity_b_organisation,entity_b_organisation_name,entity_b_entry_date,entity_b_end_date,entity_b_geometry,lookup-org-a,lookup-org-b,lookup-same-org,in-odp
0,article-4-direction-area,duplicate_geometry_check,complete_match,7010002001,"Land South of Hollybush Corner, Christmas Lane...",67,Buckinghamshire Council,2025-01-08,NaN,"MULTIPOLYGON (((-0.614912 51.566611,-0.613358 ...",...,"Land South of Hollybush Corner, Farnham Common...",67,Buckinghamshire Council,2023-11-08,NaN,"MULTIPOLYGON (((-0.614912 51.566611,-0.613358 ...",local-authority:BUC,local-authority:BUC,True,True
1,article-4-direction-area,duplicate_geometry_check,complete_match,7010002003,"St Huberts Lane, Gerrards Cross",67,Buckinghamshire Council,2025-01-08,NaN,"MULTIPOLYGON (((-0.544983 51.569309,-0.544944 ...",...,Land on the West and North-East sides of St Hu...,67,Buckinghamshire Council,2023-11-08,NaN,"MULTIPOLYGON (((-0.544984 51.569302,-0.544928 ...",local-authority:BUC,local-authority:BUC,True,True
2,article-4-direction-area,duplicate_geometry_check,complete_match,7010002004,"Field End Farm, Sevenhills Road, Iver",67,Buckinghamshire Council,2025-01-08,NaN,"MULTIPOLYGON (((-0.534064 51.555538,-0.533399 ...",...,"Land on the North Side of Seven Hills Road, Iv...",67,Buckinghamshire Council,2023-11-08,NaN,"MULTIPOLYGON (((-0.534581 51.558254,-0.534562 ...",local-authority:BUC,local-authority:BUC,True,True
3,article-4-direction-area,duplicate_geometry_check,complete_match,7010002005,"Nursery House and Land, Kiln Lane, Hedgerley",67,Buckinghamshire Council,2025-01-08,NaN,"MULTIPOLYGON (((-0.606861 51.574774,-0.606256 ...",...,Land on South Side of Kiln Lane Hedgerley - Ag...,67,Buckinghamshire Council,2023-11-08,NaN,"MULTIPOLYGON (((-0.606861 51.574774,-0.606256 ...",local-authority:BUC,local-authority:BUC,True,True
4,article-4-direction-area,duplicate_geometry_check,complete_match,7010002006,"Church Lane, Wexham",67,Buckinghamshire Council,2025-01-08,NaN,"MULTIPOLYGON (((-0.567911 51.524160,-0.567846 ...",...,"Church lane, Wexham - Agricultural",67,Buckinghamshire Council,2023-11-08,NaN,"MULTIPOLYGON (((-0.567926 51.524222,-0.567849 ...",local-authority:BUC,local-authority:BUC,True,True

In [39]:
df_complete

,old-entity,entity,status,notes,entry-date
0,7010002001,7010002531,301,Redirect old entity complete match to LPA entity,2026-02-24
1,7010002003,7010002493,301,Redirect old entity complete match to LPA entity,2026-02-24
2,7010002004,7010002494,301,Redirect old entity complete match to LPA entity,2026-02-24
3,7010002005,7010002513,301,Redirect old entity complete match to LPA entity,2026-02-24
4,7010002006,7010002408,301,Redirect old entity complete match to LPA entity,2026-02-24
...,...,...,...,...,...
41823,7002177048,7002177049,301,Redirect old entity complete match to LPA entity,2026-02-24
41824,7002177048,7002177050,301,Redirect old entity complete match to LPA entity,2026-02-24
41825,7002177049,7002177050,301,Redirect old entity complete match to LPA entity,2026-02-24
41826,7002177103,7002177104,301,Redirect old entity complete match to LPA entity,2026-02-24
41827,7002177189,7002177190,301,Redirect old entity complete match to LPA entity,2026-02-24

In [5]:
old_entity = pd.read_csv('/Users/sianteesdale/Documents/GitHub/config/pipeline/conservation-area/old-entity.csv')

In [40]:
df_complete = df.loc[(df['message'] == 'complete_match') & (df['dataset'] == 'conservation-area')].copy()
df_complete = df_complete[['entity_a', 'entity_b']]
df_complete['status'] = 301
df_complete['notes'] = 'Redirect old entity complete match to LPA entity'
df_complete['entry-date'] = datetime.now().strftime('%Y-%m-%d')
df_complete.rename(columns={'entity_a': 'old-entity', 'entity_b': 'entity'}, inplace=True)

In [41]:
df_complete

,old-entity,entity,status,notes,entry-date
7400,44000124,44015030,301,Redirect old entity complete match to LPA entity,2026-02-24
7401,44000127,44015039,301,Redirect old entity complete match to LPA entity,2026-02-24
7402,44000129,44015019,301,Redirect old entity complete match to LPA entity,2026-02-24
7403,44000130,44015076,301,Redirect old entity complete match to LPA entity,2026-02-24
7404,44000131,44015028,301,Redirect old entity complete match to LPA entity,2026-02-24
...,...,...,...,...,...
7513,44003983,44015007,301,Redirect old entity complete match to LPA entity,2026-02-24
7514,44003984,44015011,301,Redirect old entity complete match to LPA entity,2026-02-24
7515,44004188,44015143,301,Redirect old entity complete match to LPA entity,2026-02-24
7516,44006476,44015027,301,Redirect old entity complete match to LPA entity,2026-02-24
7517,44008862,44015156,301,Redirect old entity complete match to LPA entity,2026-02-24

In [38]:
# After your concat, convert to int64
result = pd.concat([old_entity, df_complete], ignore_index=True)
result['old-entity'] = result['old-entity'].astype('Int64')  # Capital I for nullable int
result['entity'] = result['entity'].astype('Int64')

# Now display normally
result

,old-entity,status,entity,end-date,notes,entry-date,start-date
0,44000536,301,44006677,NaN,NaN,NaN,NaN
1,44000549,301,44008664,NaN,NaN,NaN,NaN
2,44000550,301,44008665,NaN,NaN,NaN,NaN
3,44000551,301,44008357,NaN,NaN,NaN,NaN
4,44000552,301,44008358,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
32090,7002177048,301,7002177049,NaN,Redirect old entity complete match to LPA entity,2026-02-24,NaN
32091,7002177048,301,7002177050,NaN,Redirect old entity complete match to LPA entity,2026-02-24,NaN
32092,7002177049,301,7002177050,NaN,Redirect old entity complete match to LPA entity,2026-02-24,NaN
32093,7002177103,301,7002177104,NaN,Redirect old entity complete match to LPA entity,2026-02-24,NaN
32094,7002177189,301,7002177190,NaN,Redirect old entity complete match to LPA entity,2026-02-24,NaN

---
## Single matches

for single match - if lookup-org-a=government-organisation:PB1164 and look-up-org-b is in ODP, check if entity-a-name and entity-b-name is same/ almost same

redirect entity-a to entity-b in the format below

entity-a,301,entity-b,,redirect old entity single match to LPA entity,today's date,

This should be added to the old-entity.csv in conservation area pipeline

In [58]:
from difflib import SequenceMatcher

df_single= df.loc[(df['message'] == 'single_match') & (df['dataset'] == 'conservation-area')].copy()
df_single = df_single.loc[(df_single['lookup-org-a'] == 'government-organisation:PB1164') & (df_single['in-odp'] == True)]#[['entity_a', 'entity_a_name', 'entity_b', 'entity_b_name']]

# Add a similarity score column
df_single['name_similarity'] = df_single.apply(
    lambda row: SequenceMatcher(None, 
                                str(row['entity_a_name']).lower(), 
                                str(row['entity_b_name']).lower()).ratio() * 100,
    axis=1
)

# Filter for similar names (e.g., > 80% similar)
similar = df_single[df_single['name_similarity'] > 80].copy()

In [59]:
similar = similar[['entity_a', 'entity_b']]
similar['status'] = 301
similar['notes'] = 'Redirect old entity single match to LPA entity'
similar['entry-date'] = datetime.now().strftime('%Y-%m-%d')
similar.rename(columns={'entity_a': 'old-entity', 'entity_b': 'entity'}, inplace=True)

In [60]:
# After your concat, convert to int64
result2 = pd.concat([old_entity, df_complete], ignore_index=True)
result2['old-entity'] = result2['old-entity'].astype('Int64')  # Capital I for nullable int
result2['entity'] = result2['entity'].astype('Int64')

# Now display normally
result2

,old-entity,status,entity,end-date,notes,entry-date,start-date
0,44000536,301,44006677,NaN,NaN,NaN,NaN
1,44000549,301,44008664,NaN,NaN,NaN,NaN
2,44000550,301,44008665,NaN,NaN,NaN,NaN
3,44000551,301,44008357,NaN,NaN,NaN,NaN
4,44000552,301,44008358,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
3795,44003983,301,44015007,NaN,Redirect old entity complete match to LPA entity,2026-02-24,NaN
3796,44003984,301,44015011,NaN,Redirect old entity complete match to LPA entity,2026-02-24,NaN
3797,44004188,301,44015143,NaN,Redirect old entity complete match to LPA entity,2026-02-24,NaN
3798,44006476,301,44015027,NaN,Redirect old entity complete match to LPA entity,2026-02-24,NaN
3799,44008862,301,44015156,NaN,Redirect old entity complete match to LPA entity,2026-02-24,NaN